{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "do-board.fullname" . }}-secret
  labels:
    {{- include "do-board.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.env.jwtSecret | quote }}
  ADMIN_EMAIL: {{ .Values.env.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.env.adminPassword | quote }}
  DATABASE_URL: {{ include "do-board.databaseUrl" . | quote }}
{{- end }}
