apiVersion: v2
name: do-board
description: Open-source customizable dashboard for TV displays
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/do-2k25-28/do-board
sources:
  - https://github.com/do-2k25-28/do-board
